import pandas as pd
from PIL import ImageTk
import PIL.Image
import tkinter
from tkinter import *
import random

characters = ["Isaac", "Magdalene", "Cain", "Judas", "???", "Eve", "Samson", "Azazel", "Lazarus", "Eden", "The Lost", "Lilith", "Keeper", "Apollyon", "The Forgotten", "Bethany", "Jacob and Esau", "Tainted\n Isaac", "Tainted\n Magdalene", "Tainted\n Cain", "Tainted\n Judas", "Tainted\n ???", "Tainted\n Eve", "Tainted\n Samson", "Tainted\n Azazel", "Tainted\n Lazarus", "Tainted\n Eden", "Tainted\n Lost", "Tainted\n Lilith", "Tainted\n Keeper", "Tainted\n Apollyon", "Tainted\n Forgotten", "Tainted\n Bethany", "Tainted\n Jacob", "Dark Judas", "Lazarus Risen", "The Soul", "Dead Tainted\n Lazarus", "Tainted\n Soul", "Dark Esau"]

window = Tk()
window.title("Isaac Guess Who")
window.geometry("800x800")
window.configure(bg = "Salmon4")

titleImage = PIL.Image.open("Title.png")
titleImage = titleImage.convert("RGBA")
titleTkImage = ImageTk.PhotoImage(titleImage)
title = Canvas(window, width = 759, height = 43, bg = "Salmon4", highlightthickness = 0)
title.pack(pady = 15)
title.create_image(0, 0, anchor = NW, image = titleTkImage)

yourPickFrame = Frame(window, bg = "Salmon4")
yourPickFrame.pack(pady = 10)

isaacImage = PIL.Image.open("Isaac.png")
isaacTkImage = ImageTk.PhotoImage(isaacImage)
maggyImage = PIL.Image.open("Magdalene.png")
maggyTkImage = ImageTk.PhotoImage(maggyImage)
cainImage = PIL.Image.open("Cain.png")
cainTkImage = ImageTk.PhotoImage(cainImage)
judasImage = PIL.Image.open("Judas.png")
judasTkImage = ImageTk.PhotoImage(judasImage)
bbImage = PIL.Image.open("BB.png")
bbTkImage = ImageTk.PhotoImage(bbImage)
eveImage = PIL.Image.open("Eve.png")
eveTkImage = ImageTk.PhotoImage(eveImage)
samsonImage = PIL.Image.open("Samson.png")
samsonTkImage = ImageTk.PhotoImage(samsonImage)
azazelImage = PIL.Image.open("Azazel.png")
azazelTkImage = ImageTk.PhotoImage(azazelImage)
lazImage = PIL.Image.open("Lazarus.png")
lazTkImage = ImageTk.PhotoImage(lazImage)
edenImage = PIL.Image.open("Eden.png")
edenTkImage = ImageTk.PhotoImage(edenImage)
lostImage = PIL.Image.open("The Lost.png")
lostTkImage = ImageTk.PhotoImage(lostImage)
lilithImage = PIL.Image.open("Lilith.png")
lilithTkImage = ImageTk.PhotoImage(lilithImage)
keeperImage = PIL.Image.open("Keeper.png")
keeperTkImage = ImageTk.PhotoImage(keeperImage)
apollyonImage = PIL.Image.open("Apollyon.png")
apollyonTkImage = ImageTk.PhotoImage(apollyonImage)
forgorImage = PIL.Image.open("The Forgotten.png")
forgorTkImage = ImageTk.PhotoImage(forgorImage)
bethanyImage = PIL.Image.open("Bethany.png")
bethanyTkImage = ImageTk.PhotoImage(bethanyImage)
jAndEImage = PIL.Image.open("Jacob and Esau.png")
jAndETkImage = ImageTk.PhotoImage(jAndEImage)

tisaacImage = PIL.Image.open("TIsaac.png")
tisaacTkImage = ImageTk.PhotoImage(tisaacImage)
tmaggyImage = PIL.Image.open("TMagdalene.png")
tmaggyTkImage = ImageTk.PhotoImage(tmaggyImage)
tcainImage = PIL.Image.open("TCain.png")
tcainTkImage = ImageTk.PhotoImage(tcainImage)
tjudasImage = PIL.Image.open("TJudas.png")
tjudasTkImage = ImageTk.PhotoImage(tjudasImage)
tbbImage = PIL.Image.open("TBB.png")
tbbTkImage = ImageTk.PhotoImage(tbbImage)
teveImage = PIL.Image.open("TEve.png")
teveTkImage = ImageTk.PhotoImage(teveImage)
tsamsonImage = PIL.Image.open("TSamson.png")
tsamsonTkImage = ImageTk.PhotoImage(tsamsonImage)
tazazelImage = PIL.Image.open("TAzazel.png")
tazazelTkImage = ImageTk.PhotoImage(tazazelImage)
tlazImage = PIL.Image.open("TLazarus.png")
tlazTkImage = ImageTk.PhotoImage(tlazImage)
tedenImage = PIL.Image.open("TEden.png")
tedenTkImage = ImageTk.PhotoImage(tedenImage)
tlostImage = PIL.Image.open("TLost.png")
tlostTkImage = ImageTk.PhotoImage(tlostImage)
tlilithImage = PIL.Image.open("TLilith.png")
tlilithTkImage = ImageTk.PhotoImage(tlilithImage)
tkeeperImage = PIL.Image.open("TKeeper.png")
tkeeperTkImage = ImageTk.PhotoImage(tkeeperImage)
tapollyonImage = PIL.Image.open("TApollyon.png")
tapollyonTkImage = ImageTk.PhotoImage(tapollyonImage)
tforgorImage = PIL.Image.open("TForgotten.png")
tforgorTkImage = ImageTk.PhotoImage(tforgorImage)
tbethanyImage = PIL.Image.open("TBethany.png")
tbethanyTkImage = ImageTk.PhotoImage(tbethanyImage)
tjAndEImage = PIL.Image.open("TJacob.png")
tjAndETkImage = ImageTk.PhotoImage(tjAndEImage)

djudasImage = PIL.Image.open("Dark Judas.png")
djudasTkImage = ImageTk.PhotoImage(djudasImage)
lazRisenImage = PIL.Image.open("Lazarus Risen.png")
lazRisenTkImage = ImageTk.PhotoImage(lazRisenImage)
soulImage = PIL.Image.open("The Soul.png")
soulTkImage = ImageTk.PhotoImage(soulImage)
dTLazImage = PIL.Image.open("Dead TLazarus.png")
dTLazTkImage = ImageTk.PhotoImage(dTLazImage)
tsoulImage = PIL.Image.open("TSoul.png")
tsoulTkImage = ImageTk.PhotoImage(tsoulImage)
dEsauImage = PIL.Image.open("Dark Esau.png")
dEsauTkImage = ImageTk.PhotoImage(dEsauImage)

imageList = [isaacTkImage, maggyTkImage, cainTkImage, judasTkImage, bbTkImage, eveTkImage, samsonTkImage, azazelTkImage, lazTkImage, edenTkImage, lostTkImage, lilithTkImage, keeperTkImage, apollyonTkImage, forgorTkImage, bethanyTkImage, jAndETkImage,
             tisaacTkImage, tmaggyTkImage, tcainTkImage, tjudasTkImage, tbbTkImage,  teveTkImage, tsamsonTkImage, tazazelTkImage, tlazTkImage, tedenTkImage, tlostTkImage, tlilithTkImage, tkeeperTkImage, tapollyonTkImage, tforgorTkImage, tbethanyTkImage, tjAndETkImage,
             djudasTkImage, lazRisenTkImage, soulTkImage, dTLazTkImage, tsoulTkImage, dEsauTkImage]

def randomCharacter():
    yourCharacterPicture.delete("all") #Clears the canvas of the character

    tempPick = random.randint(0, len(characters)-1)
    yourPickText = characters[tempPick]
    yourPickPicture = imageList[tempPick]

    yourCharacterLabel.config(text = yourPickText)
    yourCharacterPicture.create_image(35, 24, anchor = CENTER, image = yourPickPicture)

randomizeLabel = Label(yourPickFrame, text = "Pick random\n character:", bg = "Salmon4", font = "bold") #Fuck you Tyler
randomizeButton = Button(yourPickFrame, command = randomCharacter, text = "Randomize")

characterFrame = Frame(yourPickFrame, bg = "Salmon4")
yourCharacterLabel = Label(characterFrame, text = "Your Character", bg = "Salmon4", font = "bold")
yourCharacterPicture = Canvas(characterFrame, width = 70, height = 48, bg = "Salmon4", highlightthickness = 0)

randomizeLabel.pack(side = LEFT, padx = 5)
randomizeButton.pack(side = LEFT, padx = 5)

characterFrame.pack(side = LEFT, pady = 5)
yourCharacterLabel.pack()
yourCharacterPicture.pack()

row1Frame = Frame(window, bg = "Salmon4")
row2Frame = Frame(window, bg = "Salmon4")
row3Frame = Frame(window, bg = "Salmon4")
row4Frame = Frame(window, bg = "Salmon4")
row5Frame = Frame(window, bg = "Salmon4")
row6Frame = Frame(window, bg = "Salmon4")
row7Frame = Frame(window, bg = "Salmon4")

def buttonPress(Button):
    Button.config(activebackground = "grey", bg = "grey", relief = SUNKEN)

isaacButton = Button(row1Frame, activebackground = "salmon1", bg = "tomato4", command = lambda:buttonPress(isaacButton), text = "Isaac", image = isaacTkImage, compound = BOTTOM)
maggyButton = Button(row1Frame, activebackground = "salmon1", bg = "tomato4", command = lambda:buttonPress(maggyButton), text = "Magdalene", image = maggyTkImage, compound = BOTTOM)
cainButton = Button(row1Frame, activebackground = "salmon1", bg = "tomato4", command = lambda:buttonPress(cainButton), text = "Cain", image = cainTkImage, compound = BOTTOM)
judasButton = Button(row1Frame, activebackground = "salmon1", bg = "tomato4", command = lambda:buttonPress(judasButton), text = "Judas", image = judasTkImage, compound = BOTTOM)
bbButton = Button(row1Frame, activebackground = "salmon1", bg = "tomato4", command = lambda:buttonPress(bbButton), text = "???", image = bbTkImage, compound = BOTTOM)
eveButton = Button(row1Frame, activebackground = "salmon1", bg = "tomato4", command = lambda:buttonPress(eveButton), text = "Eve", image = eveTkImage, compound = BOTTOM)

samsonButton = Button(row2Frame, activebackground = "salmon1", bg = "tomato4", command = lambda:buttonPress(samsonButton), text = "Samson", image = samsonTkImage, compound = BOTTOM)
azazelButton = Button(row2Frame, activebackground = "salmon1", bg = "tomato4", command = lambda:buttonPress(azazelButton), text = "Azazel", image = azazelTkImage, compound = BOTTOM)
lazButton = Button(row2Frame, activebackground = "salmon1", bg = "tomato4", command = lambda:buttonPress(lazButton), text = "Lazarus", image = lazTkImage, compound = BOTTOM)
edenButton = Button(row2Frame, activebackground = "salmon1", bg = "tomato4", command = lambda:buttonPress(edenButton), text = "Eden", image = edenTkImage, compound = BOTTOM)
lostButton = Button(row2Frame, activebackground = "salmon1", bg = "tomato4", command = lambda:buttonPress(lostButton), text = "The Lost", image = lostTkImage, compound = BOTTOM)

lilithButton = Button(row3Frame, activebackground = "salmon1", bg = "tomato4", command = lambda:buttonPress(lilithButton), text = "Lilith", image = lilithTkImage, compound = BOTTOM)
keeperButton = Button(row3Frame, activebackground = "salmon1", bg = "tomato4", command = lambda:buttonPress(keeperButton), text = "Keeper", image = keeperTkImage, compound = BOTTOM)
apollyonButton = Button(row3Frame, activebackground = "salmon1", bg = "tomato4", command = lambda:buttonPress(apollyonButton), text = "Apollyon", image = apollyonTkImage, compound = BOTTOM)
forgorButton = Button(row3Frame, activebackground = "salmon1", bg = "tomato4", command = lambda:buttonPress(forgorButton), text = "The Forgotten", image = forgorTkImage, compound = BOTTOM)
bethanyButton = Button(row3Frame, activebackground = "salmon1", bg = "tomato4", command = lambda:buttonPress(bethanyButton), text = "Bethany", image = bethanyTkImage, compound = BOTTOM)
jAndEButton = Button(row3Frame, activebackground = "salmon1", bg = "tomato4", command = lambda:buttonPress(jAndEButton), text = "Jacob and Esau", image = jAndETkImage, compound = BOTTOM)

tisaacButton = Button(row4Frame, activebackground = "salmon1", bg = "tomato4", command = lambda:buttonPress(tisaacButton), text = "Tainted\n Isaac", image = tisaacTkImage, compound = BOTTOM)
tmaggyButton = Button(row4Frame, activebackground = "salmon1", bg = "tomato4", command = lambda:buttonPress(tmaggyButton), text = "Tainted\n Magdalene", image = tmaggyTkImage, compound = BOTTOM)
tcainButton = Button(row4Frame, activebackground = "salmon1", bg = "tomato4", command = lambda:buttonPress(tcainButton), text = "Tainted\n Cain", image = tcainTkImage, compound = BOTTOM)
tjudasButton = Button(row4Frame, activebackground = "salmon1", bg = "tomato4", command = lambda:buttonPress(tjudasButton), text = "Tainted\n Judas", image = tjudasTkImage, compound = BOTTOM)
tbbButton = Button(row4Frame, activebackground = "salmon1", bg = "tomato4", command = lambda:buttonPress(tbbButton), text = "Tainted\n ???", image = tbbTkImage, compound = BOTTOM)
teveButton = Button(row4Frame, activebackground = "salmon1", bg = "tomato4", command = lambda:buttonPress(teveButton), text = "Tainted\n Eve", image = teveTkImage, compound = BOTTOM)

tsamsonButton = Button(row5Frame, activebackground = "salmon1", bg = "tomato4", command = lambda:buttonPress(tsamsonButton), text = "Tainted\n Samson", image = tsamsonTkImage, compound = BOTTOM)
tazazelButton = Button(row5Frame, activebackground = "salmon1", bg = "tomato4", command = lambda:buttonPress(tazazelButton), text = "Tainted\n Azazel", image = tazazelTkImage, compound = BOTTOM)
tlazButton = Button(row5Frame, activebackground = "salmon1", bg = "tomato4", command = lambda:buttonPress(tlazButton), text = "Tainted\n Lazarus", image = tlazTkImage, compound = BOTTOM)
tedenButton = Button(row5Frame, activebackground = "salmon1", bg = "tomato4", command = lambda:buttonPress(tedenButton), text = "Tainted\n Eden", image = tedenTkImage, compound = BOTTOM)
tlostButton = Button(row5Frame, activebackground = "salmon1", bg = "tomato4", command = lambda:buttonPress(tlostButton), text = "Tainted\n Lost", image = tlostTkImage, compound = BOTTOM)

tlilithButton = Button(row6Frame, activebackground = "salmon1", bg = "tomato4", command = lambda:buttonPress(tlilithButton), text = "Tainted\n Lilith", image = tlilithTkImage, compound = BOTTOM)
tkeeperButton = Button(row6Frame, activebackground = "salmon1", bg = "tomato4", command = lambda:buttonPress(tkeeperButton), text = "Tainted\n Keeper", image = tkeeperTkImage, compound = BOTTOM)
tapollyonButton = Button(row6Frame, activebackground = "salmon1", bg = "tomato4", command = lambda:buttonPress(tapollyonButton), text = "Tainted\n Apollyon", image = tapollyonTkImage, compound = BOTTOM)
tforgorButton = Button(row6Frame, activebackground = "salmon1", bg = "tomato4", command = lambda:buttonPress(tforgorButton), text = "Tainted\n Forgotten", image = tforgorTkImage, compound = BOTTOM)
tbethanyButton = Button(row6Frame, activebackground = "salmon1", bg = "tomato4", command = lambda:buttonPress(tbethanyButton), text = "Tainted\n Bethany", image = tbethanyTkImage, compound = BOTTOM)
tjAndEButton = Button(row6Frame, activebackground = "salmon1", bg = "tomato4", command = lambda:buttonPress(tjAndEButton), text = "Tainted\n Jacob", image = tjAndETkImage, compound = BOTTOM)

djudasButton = Button(row7Frame, activebackground = "salmon1", bg = "tomato4", command = lambda:buttonPress(djudasButton), text = "Dark Judas", image = djudasTkImage, compound = BOTTOM)
lazRisenButton = Button(row7Frame, activebackground = "salmon1", bg = "tomato4", command = lambda:buttonPress(lazRisenButton), text = "Lazarus Risen", image = lazRisenTkImage, compound = BOTTOM)
soulButton = Button(row7Frame, activebackground = "salmon1", bg = "tomato4", command = lambda:buttonPress(soulButton), text = "The Soul", image = soulTkImage, compound = BOTTOM)
dTLazButton = Button(row7Frame, activebackground = "salmon1", bg = "tomato4", command = lambda:buttonPress(dTLazButton), text = "Dead Tainted\n Lazarus", image = dTLazTkImage, compound = BOTTOM)
tsoulButton = Button(row7Frame, activebackground = "salmon1", bg = "tomato4", command = lambda:buttonPress(tsoulButton), text = "Tainted\n Soul", image = tsoulTkImage, compound = BOTTOM)
dEsauButton = Button(row7Frame, activebackground = "salmon1", bg = "tomato4", command = lambda:buttonPress(dEsauButton), text = "Dark Esau", image = dEsauTkImage, compound = BOTTOM)

row1Frame.pack()
isaacButton.pack(side = LEFT)
maggyButton.pack(side = LEFT)
cainButton.pack(side = LEFT)
judasButton.pack(side = LEFT)
bbButton.pack(side = LEFT)
eveButton.pack(side = LEFT)

row2Frame.pack()
samsonButton.pack(side = LEFT)
azazelButton.pack(side = LEFT)
lazButton.pack(side = LEFT)
edenButton.pack(side = LEFT)
lostButton.pack(side = LEFT)

row3Frame.pack()
lilithButton.pack(side = LEFT)
keeperButton.pack(side = LEFT)
apollyonButton.pack(side = LEFT)
forgorButton.pack(side = LEFT)
bethanyButton.pack(side = LEFT)
jAndEButton.pack(side = LEFT)

row4Frame.pack()
tisaacButton.pack(side = LEFT)
tmaggyButton.pack(side = LEFT)
tcainButton.pack(side = LEFT)
tjudasButton.pack(side = LEFT)
tbbButton.pack(side = LEFT)
teveButton.pack(side = LEFT)

row5Frame.pack()
tsamsonButton.pack(side = LEFT)
tazazelButton.pack(side = LEFT)
tlazButton.pack(side = LEFT)
tedenButton.pack(side = LEFT)
tlostButton.pack(side = LEFT)

row6Frame.pack()
tlilithButton.pack(side = LEFT)
tkeeperButton.pack(side = LEFT)
tapollyonButton.pack(side = LEFT)
tforgorButton.pack(side = LEFT)
tbethanyButton.pack(side = LEFT)
tjAndEButton.pack(side = LEFT)

row7Frame.pack()
djudasButton.pack(side = LEFT)
lazRisenButton.pack(side = LEFT)
soulButton.pack(side = LEFT)
dTLazButton.pack(side = LEFT)
tsoulButton.pack(side = LEFT)
dEsauButton.pack(side = LEFT)

def resetAllButtons():
    isaacButton.config(activebackground = "salmon1", bg = "tomato4", relief = RAISED)
    maggyButton.config(activebackground = "salmon1", bg = "tomato4", relief = RAISED)
    cainButton.config(activebackground = "salmon1", bg = "tomato4", relief = RAISED)
    judasButton.config(activebackground = "salmon1", bg = "tomato4", relief = RAISED)
    bbButton.config(activebackground = "salmon1", bg = "tomato4", relief = RAISED)
    eveButton.config(activebackground = "salmon1", bg = "tomato4", relief = RAISED)
    samsonButton.config(activebackground = "salmon1", bg = "tomato4", relief = RAISED)
    azazelButton.config(activebackground = "salmon1", bg = "tomato4", relief = RAISED)
    lazButton.config(activebackground = "salmon1", bg = "tomato4", relief = RAISED)
    edenButton.config(activebackground = "salmon1", bg = "tomato4", relief = RAISED)
    lostButton.config(activebackground = "salmon1", bg = "tomato4", relief = RAISED)
    lilithButton.config(activebackground = "salmon1", bg = "tomato4", relief = RAISED)
    keeperButton.config(activebackground = "salmon1", bg = "tomato4", relief = RAISED)
    apollyonButton.config(activebackground = "salmon1", bg = "tomato4", relief = RAISED)
    forgorButton.config(activebackground = "salmon1", bg = "tomato4", relief = RAISED)
    bethanyButton.config(activebackground = "salmon1", bg = "tomato4", relief = RAISED)
    jAndEButton.config(activebackground = "salmon1", bg = "tomato4", relief = RAISED)
    tisaacButton.config(activebackground = "salmon1", bg = "tomato4", relief = RAISED)
    tmaggyButton.config(activebackground = "salmon1", bg = "tomato4", relief = RAISED)
    tcainButton.config(activebackground = "salmon1", bg = "tomato4", relief = RAISED)
    tjudasButton.config(activebackground = "salmon1", bg = "tomato4", relief = RAISED)
    tbbButton.config(activebackground = "salmon1", bg = "tomato4", relief = RAISED)
    teveButton.config(activebackground = "salmon1", bg = "tomato4", relief = RAISED)
    tsamsonButton.config(activebackground = "salmon1", bg = "tomato4", relief = RAISED)
    tazazelButton.config(activebackground = "salmon1", bg = "tomato4", relief = RAISED)
    tlazButton.config(activebackground = "salmon1", bg = "tomato4", relief = RAISED)
    tedenButton.config(activebackground = "salmon1", bg = "tomato4", relief = RAISED)
    tlostButton.config(activebackground = "salmon1", bg = "tomato4", relief = RAISED)
    tlilithButton.config(activebackground = "salmon1", bg = "tomato4", relief = RAISED)
    tkeeperButton.config(activebackground = "salmon1", bg = "tomato4", relief = RAISED)
    tapollyonButton.config(activebackground = "salmon1", bg = "tomato4", relief = RAISED)
    tforgorButton.config(activebackground = "salmon1", bg = "tomato4", relief = RAISED)
    tbethanyButton.config(activebackground = "salmon1", bg = "tomato4", relief = RAISED)
    tjAndEButton.config(activebackground = "salmon1", bg = "tomato4", relief = RAISED)
    djudasButton.config(activebackground = "salmon1", bg = "tomato4", relief = RAISED)
    lazRisenButton.config(activebackground = "salmon1", bg = "tomato4", relief = RAISED)
    soulButton.config(activebackground = "salmon1", bg = "tomato4", relief = RAISED)
    dTLazButton.config(activebackground = "salmon1", bg = "tomato4", relief = RAISED)
    tsoulButton.config(activebackground = "salmon1", bg = "tomato4", relief = RAISED)
    dEsauButton.config(activebackground = "salmon1", bg = "tomato4", relief = RAISED)
    

resetButton = Button(window, command = resetAllButtons, text = "Reset", font = "bold 12")
resetButton.pack(pady = 5)

window.mainloop()